# Generated by Django 5.1.4 on 2024-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='First', max_length=50),
            preserve_default=False,
        ),
    ]
