# Generated by Django 5.1.4 on 2024-12-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_hash',
        ),
    ]
