# Generated by Django 5.1.4 on 2024-12-31 15:39

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_user_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
