# Generated by Django 5.1.4 on 2025-01-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
