# Generated by Django 5.1.4 on 2025-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_team_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
