# Generated by Django 5.1.4 on 2024-12-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
        ('user', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.team'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Add to balance'), ('expense', 'Expense')], default='expense', max_length=7),
            preserve_default=False,
        ),
    ]
