# Generated by Django 5.1.4 on 2024-12-29 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_transaction_team_transaction_transaction_type'),
        ('user', '0003_team_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='tracker_tra_user_id_20cc13_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['team'], name='tracker_tra_team_id_d501df_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_hash'], name='tracker_tra_transac_4a3bff_idx'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tracker.transaction'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
