# Generated by Django 5.1.4 on 2024-12-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Add to balance'), ('expense', 'Expense')], default='expense', max_length=7),
        ),
    ]
