# Generated by Django 5.1.4 on 2024-12-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='split_custom_section',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
