# Generated by Django 5.1.4 on 2024-12-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_transaction_split_custom_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='split_custom_section',
        ),
    ]
