# Generated by Django 5.1.4 on 2024-12-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(),
        ),
    ]
