# Generated by Django 5.1.4 on 2025-01-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_subscription_renewed_at_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('add', 'Add to balance')], default='expense', max_length=7),
        ),
    ]
