# Generated by Django 5.1.4 on 2025-01-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('clothing', 'Clothing'), ('health', 'Health'), ('education', 'Education'), ('gifts', 'Gifts'), ('savings', 'Savings'), ('investment', 'Investment'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('rent', 'Rent'), ('credit', 'Credit'), ('salary', 'Salary'), ('interest', 'Interest'), ('other', 'Other')], max_length=50),
        ),
    ]
